version: '3.8'

services:
  # --- Сервис 1: База Данных (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: diploma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Сервис 2: ML Микросервис (Python) ---
  ml_service:
    build: 
      context: ./ml_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./ml_service:/app

volumes:
  postgres_data: